# Dataset Build

This notebook is split into four parts: environment setup, parameter configuration, build execution, and result inspection.

Edit only the parameter cell for normal use.

In [1]:
from pathlib import Path
import sys

repo_root = Path.cwd().parent if (Path.cwd() / 'src').exists() is False else Path.cwd()
src_root = repo_root / 'src'
if str(src_root) not in sys.path:
    sys.path.insert(0, str(src_root))

from dataset_build import BuildConfig, build_all_datasets, build_single_noise_domain
print('dataset_build imported')

dataset_build imported

## Parameters

Tune this cell only. The rest of the notebook is execution and inspection.

In [2]:
# Build mode: 'all' builds F130, F130A, and F130C together; 'single' builds one selected noise domain.
build_mode = 'all'
single_noise_dataset = 'F130'

# Input and output roots should point to the repository root.
data_root = repo_root / 'data'
output_root = repo_root / 'data' / 'dataset_build_260518'

# Split and randomization controls.
train_ratio = 0.7
random_seed = 260505
show_progress = True

# Shared signal settings.
target_sample_rate_hz = 500_000.0
window_duration_s = 0.02
t_min_s = -0.0080
t_max_s = 0.0050
t_step_s = 0.0001
w_min = 0.5
w_max = 1.5

# Flow-noise group sizes for time-neighborhood splitting.
flow_group_sizes = {
    'F130': 10,
    'F130A': 20,
    'F130C': 10,
}

# Which domains to build in 'all' mode.
selected_noise_datasets = ('F130', 'F130A', 'F130C')

config = BuildConfig(
    data_root=data_root,
    output_root=output_root,
    target_sample_rate_hz=target_sample_rate_hz,
    train_ratio=train_ratio,
    random_seed=random_seed,
    window_duration_s=window_duration_s,
    t_min_s=t_min_s,
    t_max_s=t_max_s,
    t_step_s=t_step_s,
    w_min=w_min,
    w_max=w_max,
    flow_group_sizes=flow_group_sizes,
    noise_datasets=selected_noise_datasets,
)

config

BuildConfig(data_root=WindowsPath('e:/codes/ZZ-BK/data'), output_root=WindowsPath('e:/codes/ZZ-BK/data/dataset_build_260518'), target_sample_rate_hz=500000.0, train_ratio=0.7, random_seed=260505, window_duration_s=0.02, t_min_s=-0.008, t_max_s=0.005, t_step_s=0.0001, w_min=0.5, w_max=1.5, flow_group_sizes={'F130': 10, 'F130A': 20, 'F130C': 10}, noise_datasets=('F130', 'F130A', 'F130C'))

In [4]:
print('Build preview')
print(f'build_mode = {build_mode}')
print(f'data_root = {config.data_root}')
print(f'output_root = {config.output_root}')
print(f'train_ratio = {config.train_ratio}')
print(f'random_seed = {config.random_seed}')
print(f'target_sample_rate_hz = {config.target_sample_rate_hz}')
print(f'window_duration_s = {config.window_duration_s}')
print(f't_range = [{config.t_min_s}, {config.t_max_s}] step {config.t_step_s}')
print(f'w_range = [{config.w_min}, {config.w_max}]')
print(f'flow_group_sizes = {config.flow_group_sizes}')
print(f'noise_datasets = {config.noise_datasets}')

Build preview
build_mode = all
data_root = e:\codes\ZZ-BK\data
output_root = e:\codes\ZZ-BK\data\dataset_build_260518
train_ratio = 0.7
random_seed = 260505
target_sample_rate_hz = 500000.0
window_duration_s = 0.02
t_range = [-0.008, 0.005] step 0.0001
w_range = [0.5, 1.5]
flow_group_sizes = {'F130': 10, 'F130A': 20, 'F130C': 10}
noise_datasets = ('F130', 'F130A', 'F130C')

In [5]:
if build_mode == 'all':
    result = build_all_datasets(config, show_progress=show_progress)
elif build_mode == 'single':
    result = build_single_noise_domain(
        config,
        noise_dataset=single_noise_dataset,
        show_progress=show_progress,
    )
else:
    raise ValueError(f"Unsupported build_mode: {build_mode!r}. Use 'all' or 'single'.")

result

d:\anaconda3\envs\py312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
build datasets: 100%|██████████| 6/6 [00:26<00:00,  4.36s/it]

BuildResult(config=BuildConfig(data_root=WindowsPath('e:/codes/ZZ-BK/data'), output_root=WindowsPath('e:/codes/ZZ-BK/data/dataset_build_260518'), target_sample_rate_hz=500000.0, train_ratio=0.7, random_seed=260505, window_duration_s=0.02, t_min_s=-0.008, t_max_s=0.005, t_step_s=0.0001, w_min=0.5, w_max=1.5, flow_group_sizes={'F130': 10, 'F130A': 20, 'F130C': 10}, noise_datasets=('F130', 'F130A', 'F130C')), output_root=WindowsPath('e:/codes/ZZ-BK/data/dataset_build_260518'), log_df=                                              record_id     dataset_name  \
0     BK14-FIP-500K-20260326T113208.604-mix-F130-1.4...  BK14_f130_train
1     BK14-FIP-500K-20260324T144514.792-mix-F130-0.5...  BK14_f130_train
2     BK14-FIP-500K-20260324T165943.697-mix-F130-1.0...  BK14_f130_train
3     BK14-FIP-500K-20260326T154114.966-mix-F130-0.6...  BK14_f130_train
4     BK14-FIP-500K-20260324T165943.697-mix-F130-0.9...  BK14_f130_train
...                                                 ...              ...
5288  BK14-FIP-500K-20260324T103144.841-mix-F130C-1....  BK14_f130c_test
5289  BK14-FIP-500K-20260323T120121.475-mix-F130C-0....  BK14_f130c_test
5290  BK14-FIP-500K-20260324T103144.841-mix-F130C-0....  BK14_f130c_test
5291  BK14-FIP-500K-20260325T110848.854-mix-F130C-0....  BK14_f130c_test
5292  BK14-FIP-500K-20260325T150152.655-mix-F130C-0....  BK14_f130c_test

      split sample_class                                   output_file_name  \
0     train  broken_wire  BK14-FIP-500K-20260326T113208.604-mix-F130-1.4...
1     train  broken_wire  BK14-FIP-500K-20260324T144514.792-mix-F130-0.5...
2     train  broken_wire  BK14-FIP-500K-20260324T165943.697-mix-F130-1.0...
3     train  broken_wire  BK14-FIP-500K-20260326T154114.966-mix-F130-0.6...
4     train  broken_wire  BK14-FIP-500K-20260324T165943.697-mix-F130-0.9...
...     ...          ...                                                ...
5288   test  broken_wire  BK14-FIP-500K-20260324T103144.841-mix-F130C-1....
5289   test  broken_wire  BK14-FIP-500K-20260323T120121.475-mix-F130C-0....
5290   test  broken_wire  BK14-FIP-500K-20260324T103144.841-mix-F130C-0....
5291   test  broken_wire  BK14-FIP-500K-20260325T110848.854-mix-F130C-0....
5292   test  broken_wire  BK14-FIP-500K-20260325T150152.655-mix-F130C-0....

                                       output_file_path  \
0     e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
1     e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
2     e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
3     e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
4     e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
...                                                 ...
5288  e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
5289  e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
5290  e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
5291  e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...
5292  e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...

                      source_noise_file_name  \
0      F130-FIP-200K-20260323T175021.868.npz
1      F130-FIP-500K-20260324T170008.638.npz
2      F130-FIP-500K-20260324T170006.348.npz
3      F130-FIP-500K-20260324T170006.758.npz
4      F130-FIP-500K-20260324T170007.628.npz
...                                      ...
5288  F130C-FIP-200K-20260324T100104.904.npz
5289  F130C-FIP-500K-20260324T150044.604.npz
5290  F130C-FIP-200K-20260324T100058.284.npz
5291  F130C-FIP-200K-20260324T100059.344.npz
5292  F130C-FIP-500K-20260324T170004.178.npz

                                 source_noise_file_path  \
0     e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...
1     e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...
2     e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...
3     e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...
4     e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...
...                                                 ...
5288  e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...
5289  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...
5290  e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...
5291  e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...
5292  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...

                        source_bk_file_name  \
0     BK14-FIP-500K-20260326T113208.604.npz
1     BK14-FIP-500K-20260324T144514.792.npz
2     BK14-FIP-500K-20260324T165943.697.npz
3     BK14-FIP-500K-20260326T154114.966.npz
4     BK14-FIP-500K-20260324T165943.697.npz
...                                     ...
5288  BK14-FIP-200K-20260324T103144.841.npz
5289  BK14-FIP-200K-20260323T120121.475.npz
5290  BK14-FIP-200K-20260324T103144.841.npz
5291  BK14-FIP-500K-20260325T110848.854.npz
5292  BK14-FIP-500K-20260325T150152.655.npz

                                    source_bk_file_path  ... noise_rms  \
0     e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.013445
1     e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.009668
2     e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.004376
3     e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.015135
4     e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.013690
...                                                 ...  ...       ...
5288  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.054037
5289  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.040653
5290  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.037036
5291  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.048786
5292  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...  ...  0.043502

        bk_rms  mixed_rms  resample_noise_action  resample_bk_action  \
0     0.574901   0.527535           interpolated                none
1     0.389118   0.384765                   none                none
2     0.421178   0.492352                   none                none
3     0.431936   0.268728                   none                none
4     0.444990   0.227136                   none                none
...        ...        ...                    ...                 ...
5288  0.525945   0.733862           interpolated        interpolated
5289  0.230454   0.143990                   none        interpolated
5290  0.604587   0.538597           interpolated        interpolated
5291  0.197931   0.251819           interpolated                none
5292  0.339822   0.387564                   none                none

      random_seed           build_time  builder_version   status  \
0          260505  2026-05-18T12:01:55       2026-05-05  success
1          260505  2026-05-18T12:01:55       2026-05-05  success
2          260505  2026-05-18T12:01:55       2026-05-05  success
3          260505  2026-05-18T12:01:55       2026-05-05  success
4          260505  2026-05-18T12:01:55       2026-05-05  success
...           ...                  ...              ...      ...
5288       260505  2026-05-18T12:02:21       2026-05-05  success
5289       260505  2026-05-18T12:02:21       2026-05-05  success
5290       260505  2026-05-18T12:02:21       2026-05-05  success
5291       260505  2026-05-18T12:02:21       2026-05-05  success
5292       260505  2026-05-18T12:02:21       2026-05-05  success

      error_message
0
1
2
3
4
...             ...
5288
5289
5290
5291
5292

[5293 rows x 35 columns], manifest_dfs={'bk14_split_manifest':                          source_file_name  \
0   BK14-FIP-200K-20260323T154514.886.npz
1   BK14-FIP-200K-20260323T175314.547.npz
2   BK14-FIP-500K-20260324T144514.792.npz
3   BK14-FIP-500K-20260324T165943.697.npz
4   BK14-FIP-500K-20260324T191409.332.npz
5   BK14-FIP-500K-20260325T101142.414.npz
6   BK14-FIP-500K-20260325T112509.063.npz
7   BK14-FIP-500K-20260325T154432.616.npz
8   BK14-FIP-500K-20260326T112037.689.npz
9   BK14-FIP-500K-20260326T113208.604.npz
10  BK14-FIP-500K-20260326T144819.246.npz
11  BK14-FIP-500K-20260326T151644.071.npz
12  BK14-FIP-500K-20260326T154114.966.npz
13  BK14-FIP-500K-20260326T161851.356.npz
14  BK14-FIP-500K-20260326T165112.132.npz
15  BK14-FIP-500K-20260326T170012.003.npz
16  BK14-FIP-200K-20260323T110106.536.npz
17  BK14-FIP-200K-20260323T120121.475.npz
18  BK14-FIP-200K-20260323T212024.779.npz
19  BK14-FIP-200K-20260324T103144.841.npz
20  BK14-FIP-500K-20260325T110848.854.npz
21  BK14-FIP-500K-20260325T150152.655.npz
22  BK14-FIP-500K-20260325T164159.973.npz
23  BK14-FIP-500K-20260326T095622.278.npz

                                     source_file_path dataset_source  \
0   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
1   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
2   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
3   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
4   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
5   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
6   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
7   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
8   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
9   e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
10  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
11  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
12  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
13  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
14  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
15  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
16  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
17  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
18  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
19  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
20  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
21  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
22  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14
23  e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...           BK14

          group_id  split  sample_rate_hz       timestamp_text     method  \
0   BK14_corrosion  train        200000.0  20260323T154514.886  corrosion
1   BK14_corrosion  train        200000.0  20260323T175314.547  corrosion
2         BK14_cut  train        500000.0  20260324T144514.792        cut
3         BK14_cut  train        500000.0  20260324T165943.697        cut
4         BK14_cut  train        500000.0  20260324T191409.332        cut
5   BK14_corrosion  train        500000.0  20260325T101142.414  corrosion
6         BK14_cut  train        500000.0  20260325T112509.063        cut
7   BK14_corrosion  train        500000.0  20260325T154432.616  corrosion
8   BK14_corrosion  train        500000.0  20260326T112037.689  corrosion
9         BK14_cut  train        500000.0  20260326T113208.604        cut
10        BK14_cut  train        500000.0  20260326T144819.246        cut
11  BK14_corrosion  train        500000.0  20260326T151644.071  corrosion
12  BK14_corrosion  train        500000.0  20260326T154114.966  corrosion
13        BK14_cut  train        500000.0  20260326T161851.356        cut
14  BK14_corrosion  train        500000.0  20260326T165112.132  corrosion
15        BK14_cut  train        500000.0  20260326T170012.003        cut
16        BK14_cut   test        200000.0  20260323T110106.536        cut
17  BK14_corrosion   test        200000.0  20260323T120121.475  corrosion
18        BK14_cut   test        200000.0  20260323T212024.779        cut
19        BK14_cut   test        200000.0  20260324T103144.841        cut
20  BK14_corrosion   test        500000.0  20260325T110848.854  corrosion
21  BK14_corrosion   test        500000.0  20260325T150152.655  corrosion
22        BK14_cut   test        500000.0  20260325T164159.973        cut
23  BK14_corrosion   test        500000.0  20260326T095622.278  corrosion

    random_seed
0        260505
1        260505
2        260505
3        260505
4        260505
5        260505
6        260505
7        260505
8        260505
9        260505
10       260505
11       260505
12       260505
13       260505
14       260505
15       260505
16       260505
17       260505
18       260505
19       260505
20       260505
21       260505
22       260505
23       260505  , 'f130_split_manifest':                           source_file_name  \
0    F130-FIP-200K-20260323T175018.688.npz
1    F130-FIP-200K-20260323T175018.788.npz
2    F130-FIP-200K-20260323T175018.818.npz
3    F130-FIP-200K-20260323T175018.828.npz
4    F130-FIP-200K-20260323T175018.838.npz
..                                     ...
368  F130-FIP-500K-20260324T170012.018.npz
369  F130-FIP-500K-20260324T170012.028.npz
370  F130-FIP-500K-20260324T170012.038.npz
371  F130-FIP-500K-20260324T170012.078.npz
372  F130-FIP-500K-20260324T170012.088.npz

                                      source_file_path dataset_source  \
0    e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...           F130
1    e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...           F130
2    e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...           F130
3    e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...           F130
4    e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...           F130
..                                                 ...            ...
368  e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...           F130
369  e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...           F130
370  e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...           F130
371  e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...           F130
372  e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...           F130

            group_id split  sample_rate_hz       timestamp_text method  \
0    F130_sr200_g000  test        200000.0  20260323T175018.688   None
1    F130_sr200_g000  test        200000.0  20260323T175018.788   None
2    F130_sr200_g000  test        200000.0  20260323T175018.818   None
3    F130_sr200_g000  test        200000.0  20260323T175018.828   None
4    F130_sr200_g000  test        200000.0  20260323T175018.838   None
..               ...   ...             ...                  ...    ...
368  F130_sr500_g020  test        500000.0  20260324T170012.018   None
369  F130_sr500_g020  test        500000.0  20260324T170012.028   None
370  F130_sr500_g020  test        500000.0  20260324T170012.038   None
371  F130_sr500_g020  test        500000.0  20260324T170012.078   None
372  F130_sr500_g020  test        500000.0  20260324T170012.088   None

     random_seed
0         260505
1         260505
2         260505
3         260505
4         260505
..           ...
368       260505
369       260505
370       260505
371       260505
372       260505

[373 rows x 9 columns], 'f130a_split_manifest':                             source_file_name  \
0     F130A-FIP-200K-20260323T175018.428.npz
1     F130A-FIP-200K-20260323T175018.438.npz
2     F130A-FIP-200K-20260323T175018.448.npz
3     F130A-FIP-200K-20260323T175018.458.npz
4     F130A-FIP-200K-20260323T175018.468.npz
...                                      ...
4475  F130A-FIP-500K-20260324T170012.188.npz
4476  F130A-FIP-500K-20260324T170012.198.npz
4477  F130A-FIP-500K-20260324T170012.208.npz
4478  F130A-FIP-500K-20260324T170012.218.npz
4479  F130A-FIP-500K-20260324T170012.228.npz

                                       source_file_path dataset_source  \
0     e:\codes\ZZ-BK\data\F130A\F130A-FIP-200K-20260...          F130A
1     e:\codes\ZZ-BK\data\F130A\F130A-FIP-200K-20260...          F130A
2     e:\codes\ZZ-BK\data\F130A\F130A-FIP-200K-20260...          F130A
3     e:\codes\ZZ-BK\data\F130A\F130A-FIP-200K-20260...          F130A
4     e:\codes\ZZ-BK\data\F130A\F130A-FIP-200K-20260...          F130A
...                                                 ...            ...
4475  e:\codes\ZZ-BK\data\F130A\F130A-FIP-500K-20260...          F130A
4476  e:\codes\ZZ-BK\data\F130A\F130A-FIP-500K-20260...          F130A
4477  e:\codes\ZZ-BK\data\F130A\F130A-FIP-500K-20260...          F130A
4478  e:\codes\ZZ-BK\data\F130A\F130A-FIP-500K-20260...          F130A
4479  e:\codes\ZZ-BK\data\F130A\F130A-FIP-500K-20260...          F130A

              group_id  split  sample_rate_hz       timestamp_text method  \
0     F130A_sr200_g000  train        200000.0  20260323T175018.428   None
1     F130A_sr200_g000  train        200000.0  20260323T175018.438   None
2     F130A_sr200_g000  train        200000.0  20260323T175018.448   None
3     F130A_sr200_g000  train        200000.0  20260323T175018.458   None
4     F130A_sr200_g000  train        200000.0  20260323T175018.468   None
...                ...    ...             ...                  ...    ...
4475  F130A_sr500_g082   test        500000.0  20260324T170012.188   None
4476  F130A_sr500_g083  train        500000.0  20260324T170012.198   None
4477  F130A_sr500_g083  train        500000.0  20260324T170012.208   None
4478  F130A_sr500_g083  train        500000.0  20260324T170012.218   None
4479  F130A_sr500_g083  train        500000.0  20260324T170012.228   None

      random_seed
0          260505
1          260505
2          260505
3          260505
4          260505
...           ...
4475       260505
4476       260505
4477       260505
4478       260505
4479       260505

[4480 rows x 9 columns], 'f130c_split_manifest':                            source_file_name  \
0    F130C-FIP-200K-20260323T175019.278.npz
1    F130C-FIP-200K-20260323T175019.288.npz
2    F130C-FIP-200K-20260323T175019.448.npz
3    F130C-FIP-200K-20260323T175019.568.npz
4    F130C-FIP-200K-20260323T175019.578.npz
..                                      ...
435  F130C-FIP-500K-20260324T170011.488.npz
436  F130C-FIP-500K-20260324T170011.498.npz
437  F130C-FIP-500K-20260324T170011.618.npz
438  F130C-FIP-500K-20260324T170011.798.npz
439  F130C-FIP-500K-20260324T170011.898.npz

                                      source_file_path dataset_source  \
0    e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...          F130C
1    e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...          F130C
2    e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...          F130C
3    e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...          F130C
4    e:\codes\ZZ-BK\data\F130C\F130C-FIP-200K-20260...          F130C
..                                                 ...            ...
435  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...          F130C
436  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...          F130C
437  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...          F130C
438  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...          F130C
439  e:\codes\ZZ-BK\data\F130C\F130C-FIP-500K-20260...          F130C

             group_id  split  sample_rate_hz       timestamp_text method  \
0    F130C_sr200_g000   test        200000.0  20260323T175019.278   None
1    F130C_sr200_g000   test        200000.0  20260323T175019.288   None
2    F130C_sr200_g000   test        200000.0  20260323T175019.448   None
3    F130C_sr200_g000   test        200000.0  20260323T175019.568   None
4    F130C_sr200_g000   test        200000.0  20260323T175019.578   None
..                ...    ...             ...                  ...    ...
435  F130C_sr500_g012  train        500000.0  20260324T170011.488   None
436  F130C_sr500_g013  train        500000.0  20260324T170011.498   None
437  F130C_sr500_g013  train        500000.0  20260324T170011.618   None
438  F130C_sr500_g013  train        500000.0  20260324T170011.798   None
439  F130C_sr500_g013  train        500000.0  20260324T170011.898   None

     random_seed
0         260505
1         260505
2         260505
3         260505
4         260505
..           ...
435       260505
436       260505
437       260505
438       260505
439       260505

[440 rows x 9 columns]}, summary_df=       dataset_name  split  sample_count
0    BK14_f130_test   test           109

In [6]:
print(result.report_path)
display(result.log_df.head())
display(result.summary_df)

e:\codes\ZZ-BK\data\dataset_build_260518\logs\dataset_build.md

,record_id,dataset_name,split,sample_class,output_file_name,output_file_path,source_noise_file_name,source_noise_file_path,source_bk_file_name,source_bk_file_path,...,noise_rms,bk_rms,mixed_rms,resample_noise_action,resample_bk_action,random_seed,build_time,builder_version,status,error_message
0,BK14-FIP-500K-20260326T113208.604-mix-F130-1.4...,BK14_f130_train,train,broken_wire,BK14-FIP-500K-20260326T113208.604-mix-F130-1.4...,e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...,F130-FIP-200K-20260323T175021.868.npz,e:\codes\ZZ-BK\data\F130\F130-FIP-200K-2026032...,BK14-FIP-500K-20260326T113208.604.npz,e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...,...,0.013445,0.574901,0.527535,interpolated,none,260505,2026-05-18T12:01:55,2026-05-05,success,
1,BK14-FIP-500K-20260324T144514.792-mix-F130-0.5...,BK14_f130_train,train,broken_wire,BK14-FIP-500K-20260324T144514.792-mix-F130-0.5...,e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...,F130-FIP-500K-20260324T170008.638.npz,e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...,BK14-FIP-500K-20260324T144514.792.npz,e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...,...,0.009668,0.389118,0.384765,none,none,260505,2026-05-18T12:01:55,2026-05-05,success,
2,BK14-FIP-500K-20260324T165943.697-mix-F130-1.0...,BK14_f130_train,train,broken_wire,BK14-FIP-500K-20260324T165943.697-mix-F130-1.0...,e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...,F130-FIP-500K-20260324T170006.348.npz,e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...,BK14-FIP-500K-20260324T165943.697.npz,e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...,...,0.004376,0.421178,0.492352,none,none,260505,2026-05-18T12:01:55,2026-05-05,success,
3,BK14-FIP-500K-20260326T154114.966-mix-F130-0.6...,BK14_f130_train,train,broken_wire,BK14-FIP-500K-20260326T154114.966-mix-F130-0.6...,e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...,F130-FIP-500K-20260324T170006.758.npz,e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...,BK14-FIP-500K-20260326T154114.966.npz,e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...,...,0.015135,0.431936,0.268728,none,none,260505,2026-05-18T12:01:55,2026-05-05,success,
4,BK14-FIP-500K-20260324T165943.697-mix-F130-0.9...,BK14_f130_train,train,broken_wire,BK14-FIP-500K-20260324T165943.697-mix-F130-0.9...,e:\codes\ZZ-BK\data\dataset_build_260518\BK14_...,F130-FIP-500K-20260324T170007.628.npz,e:\codes\ZZ-BK\data\F130\F130-FIP-500K-2026032...,BK14-FIP-500K-20260324T165943.697.npz,e:\codes\ZZ-BK\data\BK14-0.06S(Generation meth...,...,0.013690,0.444990,0.227136,none,none,260505,2026-05-18T12:01:55,2026-05-05,success,

       dataset_name  split  sample_count
0    BK14_f130_test   test           109
1   BK14_f130_train  train           264
2   BK14_f130a_test   test          1340
3  BK14_f130a_train  train          3140
4   BK14_f130c_test   test           130
5  BK14_f130c_train  train           310

## Example: downsample one BK14 500K sample

This cell converts one fixed BK14 500K source file to 200 kHz and saves the result to a local preview folder for inspection.

The downsampling path removes the linear trend before `resample_poly` and uses `padtype='line'` to suppress the 100 kHz Nyquist-edge artifact and edge transients.

In [ ]:
from pathlib import Path

import numpy as np

from bk_analysis.io import load_signal_record
from dataset_build.resample import resample_to_rate
from dataset_build.writers import write_npz

example_source = repo_root / 'data' / 'BK14-0.06S(Generation method)' / 'corrosion' / 'BK14-FIP-500K-20260325T101142.414.npz'
example_output_root = repo_root / 'data' / 'downsample_preview'
example_output_root.mkdir(parents=True, exist_ok=True)
example_output_path = example_output_root / f'{example_source.stem}-sr200k.npz'

with np.load(example_source, allow_pickle=True) as raw:
    original_timestamp = float(raw['timestamp'])
    original_starttime = str(raw['starttime'].tolist())
    original_arrival_time = str(raw['arrival_time'].tolist())
    original_sample_type = str(raw['type'].tolist())
    original_data_info = raw['data_info'].item() if 'data_info' in raw else {}

record = load_signal_record(example_source, method='corrosion')
resampled_signal, resample_action = resample_to_rate(record.signal, record.sample_rate, 200_000.0)

data_info = dict(original_data_info) if isinstance(original_data_info, dict) else {}
data_info.update(
    {
        'example_source_file': example_source.name,
        'example_target_sample_rate_hz': 200_000.0,
        'example_resample_action': resample_action,
        'example_note': 'single BK14 500K sample downsampled to 200K for manual inspection',
    }
)

write_npz(
    output_path=example_output_path,
    signal_values=resampled_signal,
    sample_rate_hz=200_000.0,
    starttime=original_starttime,
    arrival_time=original_arrival_time,
    timestamp=original_timestamp,
    sample_type=original_sample_type,
    data_info=data_info,
)

f = np.fft.rfftfreq(len(resampled_signal), d=1 / 200_000.0)
m = np.abs(np.fft.rfft(resampled_signal))
top = np.argsort(m)[-8:][::-1]

print(f'source: {example_source}')
print(f'output: {example_output_path}')
print(f'original_len = {len(record.signal)}')
print(f'resampled_len = {len(resampled_signal)}')
print(f'resample_action = {resample_action}')
print('top spectral peaks (Hz, magnitude):')
for idx in top:
    print(f'  {float(f[idx]):.1f}, {float(m[idx]):.6f}')

## Example: upsample one BK14 200K sample

This cell upsamples one fixed BK14 200K source file to 500 kHz and saves the result to a local preview folder for comparison.

In [ ]:
from pathlib import Path

import numpy as np

from bk_analysis.io import load_signal_record
from dataset_build.resample import resample_to_rate
from dataset_build.writers import write_npz

upsample_source = repo_root / 'data' / 'BK14-0.06S(Generation method)' / 'corrosion' / 'BK14-FIP-200K-20260323T120121.475.npz'
upsample_output_root = repo_root / 'data' / 'upsample_preview'
upsample_output_root.mkdir(parents=True, exist_ok=True)
upsample_output_path = upsample_output_root / f'{upsample_source.stem}-sr500k.npz'

with np.load(upsample_source, allow_pickle=True) as raw:
    original_timestamp = float(raw['timestamp'])
    original_starttime = str(raw['starttime'].tolist())
    original_arrival_time = str(raw['arrival_time'].tolist())
    original_sample_type = str(raw['type'].tolist())
    original_data_info = raw['data_info'].item() if 'data_info' in raw else {}

record = load_signal_record(upsample_source, method='corrosion')
upsampled_signal, resample_action = resample_to_rate(record.signal, record.sample_rate, 500_000.0)

data_info = dict(original_data_info) if isinstance(original_data_info, dict) else {}
data_info.update(
    {
        'example_source_file': upsample_source.name,
        'example_target_sample_rate_hz': 500_000.0,
        'example_resample_action': resample_action,
        'example_note': 'single BK14 200K sample upsampled to 500K for manual comparison',
    }
)

write_npz(
    output_path=upsample_output_path,
    signal_values=upsampled_signal,
    sample_rate_hz=500_000.0,
    starttime=original_starttime,
    arrival_time=original_arrival_time,
    timestamp=original_timestamp,
    sample_type=original_sample_type,
    data_info=data_info,
)

f = np.fft.rfftfreq(len(upsampled_signal), d=1 / 500_000.0)
m = np.abs(np.fft.rfft(upsampled_signal))
top = np.argsort(m)[-8:][::-1]

print(f'source: {upsample_source}')
print(f'output: {upsample_output_path}')
print(f'original_len = {len(record.signal)}')
print(f'upsampled_len = {len(upsampled_signal)}')
print(f'resample_action = {resample_action}')
print('top spectral peaks (Hz, magnitude):')
for idx in top:
    print(f'  {float(f[idx]):.1f}, {float(m[idx]):.6f}')

print('first10:', np.round(upsampled_signal[:10], 3).tolist())
print('last10:', np.round(upsampled_signal[-10:], 3).tolist())
print('max diff first50:', float(np.max(np.abs(np.diff(upsampled_signal)[:50]))))
print('max diff last50:', float(np.max(np.abs(np.diff(upsampled_signal)[-50:]))))